# -*- coding: utf-8 -*-
"""2420080031_WEEK3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19dBpQmGZ6oXyG0F8tFLGHrPTzvbddiVg
"""

from sklearn.datasets import load_iris
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import MinMaxScaler
from sklearn.decomposition import PCA
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

data = load_iris()
x = data.data
y = data.target
target_names = data.target_names
print("Original data shape:" , x.shape)

scaler = StandardScaler()
x_Standardization = scaler.fit_transform(x)

minmax = MinMaxScaler()
x_normalized = minmax.fit_transform(x)

pca = PCA(n_components = 2)
x_pca = pca.fit_transform(x_Standardization)

print("\nExplained variance ratio:")
for i,var in enumerate (pca.explained_variance_ratio_):
  print(f"principal component{i + 1}:{var: 4f}")
print("\ncumulative  explained variance:",np.cumsum(pca.explained_variance_ratio_))

pca_full = PCA()
pca_full.fit(x_Standardization)
plt.figure()
plt.plot(np.cumsum(pca_full.explained_variance_ratio_),marker='o')
plt.xlabel("Number of components")
plt.ylabel("Cumulative explained variance")
plt.title("Screen plot")
plt.grid()
plt.show()

#original data
plt.figure()
for i,target in enumerate(target_names):
  plt.scatter(x_Standardization[y == i,0],x_Standardization[y == i,1], label = target)
plt.xlabel("Feature 1")
plt.ylabel("Feature 2")
plt.title("Original data (First two Features)")
plt.legend()
plt.show()

#PCA-transformed data
plt.figure()
for i,target in enumerate(target_names):
  plt.scatter(x_pca[y == i,0], x_pca[y == i,1] , label = target)
plt.xlabel("PC1")
plt.ylabel("PC2")
plt.title("PCA-Transformed Data")
plt.legend()
plt.show()